### ISSUE TITLE
Multi NFT markers

### ISSUE THREAD

**Issue by kalwalt** [webarkit/jsartoolkit5#4]
Hi @hiukim i'm testing your code that we discussed in the issue https://github.com/artoolkitx/jsartoolkit5/issues/95 in regards of your branch https://github.com/hiukim/jsartoolkit5/tree/fixnft Have you an example for testing the `loadNFTMarkers` ?

**Comment by hiukim** [comment]
@kalwalt Unfortunately, I don't have a standalone example. But I suppose it you can first test it with the `loadNFTMarker`, which use `loadNFTMarkers`.  The signature for `loadNFTMarker` is the same, so your existing code should work without making any changes. 

I'm happy to help debug if you have found any errors.

**Comment by kalwalt** [comment]
> @kalwalt Unfortunately, I don't have a standalone example. But I suppose it you can first test it with the `loadNFTMarker`, which use `loadNFTMarkers`. The signature for `loadNFTMarker` is the same, so your existing code should work without making any changes.
> 
> I'm happy to help debug if you have found any errors.

i already tested the basic example with the sphere, it seems to works well, i can't see any flaws, maybe is more fluid? I will try to setup a minimal example loading multi NFT. I can not say when but it's on my to do list. Have you seen also that i created a github team?

**Comment by hiukim** [comment]
@kalwalt  nice. let me know if you encountered any error.       

the webarkit team? I think I'm in already.

**Comment by kalwalt** [comment]
> @kalwalt nice. let me know if you encountered any error.
> 
> the webarkit team? I think I'm in already.

Thank you, yes you are already in, just to know if the post i created is visible or not. It should be here https://github.com/orgs/webarkit/teams/webarkit/discussions/1

**Comment by hiukim** [comment]
@kalwalt  Yes. I can see it now. :)

**Comment by ThorstenBux** [comment]
I just merged all changes from @hiukim into our repo. This is probably breaking a whole lot of stuff but it is worth it :)
