### ISSUE TITLE
Fix examples to work with new multi NFT version

### ISSUE THREAD

**Issue by ThorstenBux** [webarkit/jsartoolkit5#8]
It's needed to update the NFT examples and provide at least a working example with new multi NFT markers.

**Comment by kalwalt** [comment]
Hi to all! @hiukim could you provide a simple example with the new **loadNFTMarkers**? It will be much appreciated. If you can you can directly works on a branch (you should have permission) or i can create me and you have only to pull, or you can share if you prefer a gist. Thank you! :slightly_smiling_face:

**Comment by hiukim** [comment]
I haven't been using this for a while, so I'm not sure I can hack an example quickly.

However, if I remember correctly, the API for loadNFTMarkers is more or less the same as loadNFTMarker, but taking an array instead. i.e.

`loadNFTMarkers([marker1, marker2])`
vs
`loadNFTMarker(marker1)

**Comment by kalwalt** [comment]
> I haven't been using this for a while, so I'm not sure I can hack an example quickly.
> 
> However, if I remember correctly, the API for loadNFTMarkers is more or less the same as loadNFTMarker, but taking an array instead. i.e.
> 
> `loadNFTMarkers([marker1, marker2])`
> vs
> `loadNFTMarker(marker1)`
> 
> Maybe you can try a simple case of replacing loadNFTMarker with loadNFTMarkers in a working example? I can help look at the error if there is any.

I tried again yesterday, and i was able to run a minimal example. Simple like water, don't know what issues i had the other day... Soon i will create a branch and a PR. It is important also to update all the other NFT examples. :smile:

**Comment by hiukim** [comment]
> > I haven't been using this for a while, so I'm not sure I can hack an example quickly.
> > However, if I remember correctly, the API for loadNFTMarkers is more or less the same as loadNFTMarker, but taking an array instead. i.e.
> > `loadNFTMarkers([marker1, marker2])`
> > vs
> > `loadNFTMarker(marker1)`
> > Maybe you can try a simple case of replacing loadNFTMarker with loadNFTMarkers in a working example? I can help look at the error if there is any.
> 
> I tried again yesterday, and i was able to run a minimal example. Simple like water, don't know what issues i had the other day... Soon i will create a branch and a PR. It is important also to update all the other NFT examples. 😄

Nice! Just post the error if you encountered any.

**Comment by kalwalt** [comment]
Your code is a nice improvement! I tice also better performances, or i am wrong? Maybe we should test new with old code... :thinking:

**Comment by hiukim** [comment]
> Your code is a nice improvement! I notice also better performances, or i am wrong? Maybe we should test new with old code... 🤔

I would be surprised, if that's the case. haha :)

**Comment by kalwalt** [comment]
I created a PR see #10

**Comment by kalwalt** [comment]
This was done with #10
